# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
        environment:
          TERM: xterm
    working_directory: ~/GoEats
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }} 
      - run: npm install -g wait-on
      - run: npm run start && wait-on http://localhost:1234
      - run: $(npm bin)/cypress run